DROP USER assignment_team CASCADE;

CREATE USER assignment_team IDENTIFIED BY BostonSpring2024#;

ALTER USER assignment_team DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

ALTER USER assignment_team TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO assignment_team;

GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO assignment_team;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO assignment_team;